# To run this image put the OSFM-Core-Public repo in the same folder as this dockerfile, this will become the work directory

FROM ubuntu:rolling

RUN useradd -ms /bin/bash builder
ADD OSFM-Core-Public/setup.sh /home/builder/setup.sh
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
	 sudo \
         wget \
         g++ \
         git \
         automake \
         autoconf \
         autotools-dev \
         libtool \
         ninja-build \
         bash \
         python3-pip \
         dos2unix && \
    /home/builder/setup.sh && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER builder
WORKDIR /home/builder
ENTRYPOINT ["bash"] 

# build this docker image as follows:
# docker build -t oneshot-build-linux .

# run this docker image as follows:
# docker run -i -v /path/to/modshot-core:/home/builder/work -v /path/to/gamefiles:/home/builder/data -v /path/to/distrubution/folder:/home/builder/dist oneshot-build-linux
